// /**
//  * Calculates the final authenticity score and determines the verdict.
//  * @param {object} bytez - Bytze.js prediction result.
//  * @param {Array} yandexResults - Array of Yandex search matches.
//  * @param {object} llmAnalysis - Gemini LLM analysis result.
//  * @param {object} groqEvaluation - Groq submission match result.
//  * @param {object} forensicFeatures - Extracted image features (pHash, exif, resolution, exifStripped).
//  * @returns {{total: number, verdict: string, rationale: string[]}}
//  */
// export function calculateFinalScore(
//   bytez,
//   yandexResults,
//   llmAnalysis,
//   groqEvaluation,
//   forensicFeatures
// ) {
//   let score = 0;
//   let rationale = [];

//   // --- I. AI/Manipulation Detection (Max 200 Points) ---
//   let aiScore = 0;
//   if (bytez.status === "CLEAN" || bytez.status === "MANIPULATED") {
//     // A. Bytze.js AI Score: 200 Points * (1 - manipulation_score)
//     const manipulationScore = bytez.score;
//     aiScore = Math.round(200 * (1 - manipulationScore));
//     rationale.push(`AI Check (Bytez.js): 200 * (1 - ${manipulationScore.toFixed(2)}) = +${aiScore}`);

//     // B. Metadata AI/Editor Tags (Deduction)
//     const exifNotes = JSON.stringify(forensicFeatures.exifData || {}).toLowerCase();
//     if (exifNotes.includes("photoshop") || exifNotes.includes("midjourney") || exifNotes.includes("dall-e")) {
//         aiScore = Math.max(0, aiScore - 50);
//         rationale.push(`Metadata Penalty: -50 (Found Editor/AI Signature)`);
//     }

//   } else {
//     aiScore = 100; // API Failure default score
//     rationale.push(`AI Check Failed (Default Score): +100`);
//   }
//   score += aiScore;

//   // --- II. Plagiarism/Source Check (Max 150 Points) ---
//   let plagiarismScore = 150;
//   rationale.push(`Plagiarism Check (Base Score): +150`);

//   if (yandexResults && yandexResults.length > 0) {
//     const bestMatch = yandexResults[0];

//     if (bestMatch.similarity >= 90) {
//       plagiarismScore -= 150;
//       rationale.push(`Plagiarism Penalty: -150 (Strong Match >= 90% Similarity)`);
//     } else if (bestMatch.similarity >= 70) {
//       plagiarismScore -= 75;
//       rationale.push(`Plagiarism Penalty: -75 (Moderate Match 70-89% Similarity)`);
//     }
//   }
//   score += plagiarismScore;

//   // --- III. Contextual Integrity (LLM & Groq) (Max 100 Points) ---
//   let contextualScore = 0;
  
//   // A. Gemini LLM Verdict (Max 70)
//   const geminiVerdict = (llmAnalysis.verdict || "UNKNOWN").toUpperCase();
//   if (geminiVerdict === "ORIGINAL") {
//     contextualScore += 70;
//     rationale.push(`LLM Verdict (${geminiVerdict}): +70`);
//   } else if (geminiVerdict === "MODIFIED" || geminiVerdict === "UNKNOWN") {
//     contextualScore += 35;
//     rationale.push(`LLM Verdict (${geminiVerdict}): +35`);
//   } else {
//     rationale.push(`LLM Verdict (${geminiVerdict}): +0`);
//   }

//   // B. Groq Submission Match (Max 30)
//   // Check specifically for the 'match' property to avoid status string mismatches
//   const isMatch = groqEvaluation.match === true || groqEvaluation.match === "true";
//   const groqConfidence = groqEvaluation.confidence || 0;

//   if (isMatch) {
//     const matchPoints = Math.round(30 * groqConfidence);
//     contextualScore += matchPoints;
//     rationale.push(`Groq Match (${(groqConfidence * 100).toFixed(0)}% Confidence): +${matchPoints}`);
//   } else {
//     rationale.push(`Groq Match Failed: +0`);
//   }
//   score += contextualScore;

//   // --- IV. Forensic Metadata (Max 50 Points) ---
//   let forensicScore = 50;
  
//   // A. EXIF Integrity (Max 25)
//   if (forensicFeatures.exifStripped === false) {
//     // No penalty applied
//   } else {
//     forensicScore -= 25;
//     rationale.push(`EXIF Penalty: -25 (Metadata Stripped)`);
//   }

//   // B. Resolution Check (Max 25)
//   // Logic updated: No longer deducing score based on resolution. 
//   // We simply log the resolution for the reviewer's information.
//   rationale.push(`Image Resolution: ${forensicFeatures.resolution || "Unknown"} (No Deduction)`);
  
//   forensicScore = Math.max(0, forensicScore); 
//   score += forensicScore;

//   // --- Final Verdict Tier ---
//   const totalScore = Math.round(score);
//   let finalVerdict;

//   if (totalScore >= 400) {
//     finalVerdict = "AUTHENTIC & ORIGINAL";
//   } else if (totalScore >= 300) {
//     finalVerdict = "MODERATE RISK / UNKNOWN";
//   } else if (totalScore >= 150) {
//     finalVerdict = "HIGH RISK / MODIFIED";
//   } else {
//     finalVerdict = "PLAGIARIZED / FAKE";
//   }

//   return { total: totalScore, verdict: finalVerdict, rationale };
// }




// // AI Detection	        200	      Checks if the pixels were generated by AI.
// // Plagiarism	          150	      Checks if the image already exists on the internet.
// // LLM Analysis	        70	      Expert visual inspection by Gemini.
// // Challenge Match	    30	      Checks if the image matches the prompt/task.
// // Forensics	          50	      Checks for original file metadata.
// // TOTAL	              500



































// /**
//  * Calculates the final authenticity score and determines the verdict.
//  * LLM ANALYSIS REMOVED (SAFE VERSION)
//  *
//  * @param {object} bytez - Bytez.js prediction result
//  * @param {Array} yandexResults - Reverse image search matches
//  * @param {null} llmAnalysis - UNUSED (kept for backward compatibility)
//  * @param {object} groqEvaluation - Challenge / prompt verification result
//  * @param {object} forensicFeatures - Image forensic metadata
//  * @returns {{total: number, verdict: string, rationale: string[]}}
//  */
// export function calculateFinalScore(
//   bytez,
//   yandexResults = [],
//   llmAnalysis = null,      // intentionally unused
//   groqEvaluation = {},
//   forensicFeatures = {}
// ) {
//   let score = 0;
//   let rationale = [];

//   // --------------------------------------------------
//   // I. AI / MANIPULATION DETECTION (MAX 200)
//   // --------------------------------------------------
//   let aiScore = 0;

//   if (bytez?.status === "CLEAN" || bytez?.status === "MANIPULATED") {
//     const manipulationScore = bytez.score ?? 1;
//     aiScore = Math.round(200 * (1 - manipulationScore));

//     rationale.push(
//       `AI Check (Bytez.js): 200 × (1 - ${manipulationScore.toFixed(2)}) = +${aiScore}`
//     );

//     const exifNotes = JSON.stringify(forensicFeatures.exifData || {}).toLowerCase();
//     if (
//       exifNotes.includes("photoshop") ||
//       exifNotes.includes("midjourney") ||
//       exifNotes.includes("dall-e")
//     ) {
//       aiScore = Math.max(0, aiScore - 50);
//       rationale.push("Metadata Penalty: -50 (Editor / AI Signature Found)");
//     }
//   } else {
//     aiScore = 100;
//     rationale.push("AI Check Failed (Default Score): +100");
//   }

//   score += aiScore;

//   // --------------------------------------------------
//   // II. PLAGIARISM / SOURCE CHECK (MAX 150)
//   // --------------------------------------------------
//   let plagiarismScore = 150;
//   rationale.push("Plagiarism Check (Base Score): +150");

//   if (yandexResults.length > 0) {
//     const bestMatch = yandexResults[0];

//     if (bestMatch.similarity >= 90) {
//       plagiarismScore -= 150;
//       rationale.push("Plagiarism Penalty: -150 (Strong Match ≥ 90%)");
//     } else if (bestMatch.similarity >= 70) {
//       plagiarismScore -= 75;
//       rationale.push("Plagiarism Penalty: -75 (Moderate Match 70–89%)");
//     }
//   }

//   score += plagiarismScore;

//   // --------------------------------------------------
//   // III. CONTEXTUAL / CHALLENGE VERIFICATION (MAX 100)
//   // --------------------------------------------------
//   let contextualScore = 0;

//   const isMatch =
//     groqEvaluation.match === true || groqEvaluation.match === "true";
//   const confidence = groqEvaluation.confidence ?? 0;

//   if (isMatch) {
//     contextualScore = Math.round(100 * confidence);
//     rationale.push(
//       `Challenge Match (${Math.round(confidence * 100)}% Confidence): +${contextualScore}`
//     );
//   } else {
//     rationale.push("Challenge Match Failed: +0");
//   }

//   score += contextualScore;

//   // --------------------------------------------------
//   // IV. FORENSIC METADATA CHECKS (MAX 50)
//   // --------------------------------------------------
//   let forensicScore = 50;

//   if (forensicFeatures.exifStripped) {
//     forensicScore -= 25;
//     rationale.push("EXIF Penalty: -25 (Metadata Stripped)");
//   }

//   rationale.push(
//     `Image Resolution: ${forensicFeatures.resolution || "Unknown"} (No Deduction)`
//   );

//   score += Math.max(0, forensicScore);

//   // --------------------------------------------------
//   // FINAL VERDICT
//   // --------------------------------------------------
//   const totalScore = Math.round(score);
//   let verdict;

//   if (totalScore >= 400) verdict = "AUTHENTIC & ORIGINAL";
//   else if (totalScore >= 300) verdict = "MODERATE RISK / UNKNOWN";
//   else if (totalScore >= 150) verdict = "HIGH RISK / MODIFIED";
//   else verdict = "PLAGIARIZED / FAKE";

//   return {
//     total: totalScore,
//     verdict,
//     rationale
//   };
// }










/**
 * Calculates final score based on 4-layer pipeline.
 * Layers 1 & 2 are hard gates (return 0 if failed).
 * Layers 3 & 4 are point-based (250 points each).
 *
 * @param {object} bytezPrediction - Result from Layer 1
 * @param {array} yandexResults - Result from Layer 2
 * @param {object} llmAnalysis - Result from Layer 4 (Quality)
 * @param {object} challengeEval - Result from Layer 3 (Match)
 * @returns {{total: number, rationale: string[]}}
 */
export function calculateFinalScore(
  bytezPrediction = {},
  yandexResults = [],
  llmAnalysis = {},
  challengeEval = {}
) {
  let rationale = [];
  let totalPoints = 0;

  // --- LAYER 1: AI DETECTION GATE ---
  const isAiDetected =
    bytezPrediction.status === "AI_DETECTED" ||
    bytezPrediction.status === "MANIPULATED" ||
    (bytezPrediction.score && bytezPrediction.score > 0.8);

  if (isAiDetected) {
    return {
      total: 0,
      rationale: ["AI DETECTED: Process halted, 0 points assigned."],
    };
  }

  // --- LAYER 2: REVERSE SEARCH GATE ---
  const STRONG_MATCH_THRESHOLD = 70;
  const hasStrongMatch = yandexResults.some(
    (r) => r.similarity >= STRONG_MATCH_THRESHOLD
  );

  if (hasStrongMatch) {
    return {
      total: 0,
      rationale: ["COPIED CONTENT: Reverse search match found, 0 points assigned."],
    };
  }

  // --- LAYER 3: CHALLENGE MATCHING (Max 250 Points) ---
  const isMatch = challengeEval.match === true || challengeEval.match === "true";
  const matchConfidence = Number(challengeEval.confidence || 0);
  let layer3Points = 0;

  if (isMatch) {
    layer3Points = Math.round(250 * matchConfidence);
    rationale.push(`Challenge Match: +${layer3Points}/250 (Confidence: ${(matchConfidence * 100).toFixed(0)}%)`);
  } else {
    rationale.push("Challenge Match: +0/250 (Description not satisfied)");
  }

  // --- LAYER 4: QUALITY CHECK (Max 250 Points) ---
  const qualityScore = Number(llmAnalysis.qualityScore || 0);
  const layer4Points = Math.round(250 * qualityScore);
  
  rationale.push(`Quality Score: +${layer4Points}/250 (Score: ${(qualityScore * 100).toFixed(0)}%)`);

  // --- TOTAL CALCULATION ---
  totalPoints = layer3Points + layer4Points;

  return {
    total: totalPoints,
    rationale: rationale,
  };
}