/**
 * Calculates the final authenticity score and determines the verdict.
 * @param {object} bytez - Bytze.js prediction result.
 * @param {Array} yandexResults - Array of Yandex search matches.
 * @param {object} llmAnalysis - Gemini LLM analysis result.
 * @param {object} groqEvaluation - Groq submission match result.
 * @param {object} forensicFeatures - Extracted image features (pHash, exif, resolution, exifStripped).
 * @returns {{total: number, verdict: string, rationale: string[]}}
 */
export function calculateFinalScore(
  bytez,
  yandexResults,
  llmAnalysis,
  groqEvaluation,
  forensicFeatures
) {
  let score = 0;
  let rationale = [];

  // --- I. AI/Manipulation Detection (Max 200 Points) ---
  let aiScore = 0;
  if (bytez.status === "CLEAN" || bytez.status === "MANIPULATED") {
    // A. Bytze.js AI Score: 200 Points * (1 - manipulation_score)
    const manipulationScore = bytez.score;
    aiScore = Math.round(200 * (1 - manipulationScore));
    rationale.push(`AI Check (Bytez.js): 200 * (1 - ${manipulationScore.toFixed(2)}) = +${aiScore}`);

    // B. Metadata AI/Editor Tags (Deduction)
    const exifNotes = JSON.stringify(forensicFeatures.exifData || {}).toLowerCase();
    if (exifNotes.includes("photoshop") || exifNotes.includes("midjourney") || exifNotes.includes("dall-e")) {
        aiScore = Math.max(0, aiScore - 50);
        rationale.push(`Metadata Penalty: -50 (Found Editor/AI Signature)`);
    }

  } else {
    aiScore = 100; // API Failure default score
    rationale.push(`AI Check Failed (Default Score): +100`);
  }
  score += aiScore;

  // --- II. Plagiarism/Source Check (Max 150 Points) ---
  let plagiarismScore = 150;
  rationale.push(`Plagiarism Check (Base Score): +150`);

  if (yandexResults && yandexResults.length > 0) {
    const bestMatch = yandexResults[0];

    if (bestMatch.similarity >= 90) {
      plagiarismScore -= 150;
      rationale.push(`Plagiarism Penalty: -150 (Strong Match >= 90% Similarity)`);
    } else if (bestMatch.similarity >= 70) {
      plagiarismScore -= 75;
      rationale.push(`Plagiarism Penalty: -75 (Moderate Match 70-89% Similarity)`);
    }
  }
  score += plagiarismScore;

  // --- III. Contextual Integrity (LLM & Groq) (Max 100 Points) ---
  let contextualScore = 0;
  
  // A. Gemini LLM Verdict (Max 70)
  const geminiVerdict = (llmAnalysis.verdict || "UNKNOWN").toUpperCase();
  if (geminiVerdict === "ORIGINAL") {
    contextualScore += 70;
    rationale.push(`LLM Verdict (${geminiVerdict}): +70`);
  } else if (geminiVerdict === "MODIFIED" || geminiVerdict === "UNKNOWN") {
    contextualScore += 35;
    rationale.push(`LLM Verdict (${geminiVerdict}): +35`);
  } else {
    rationale.push(`LLM Verdict (${geminiVerdict}): +0`);
  }

  // B. Groq Submission Match (Max 30)
  // Check specifically for the 'match' property to avoid status string mismatches
  const isMatch = groqEvaluation.match === true || groqEvaluation.match === "true";
  const groqConfidence = groqEvaluation.confidence || 0;

  if (isMatch) {
    const matchPoints = Math.round(30 * groqConfidence);
    contextualScore += matchPoints;
    rationale.push(`Groq Match (${(groqConfidence * 100).toFixed(0)}% Confidence): +${matchPoints}`);
  } else {
    rationale.push(`Groq Match Failed: +0`);
  }
  score += contextualScore;

  // --- IV. Forensic Metadata (Max 50 Points) ---
  let forensicScore = 50;
  
  // A. EXIF Integrity (Max 25)
  if (forensicFeatures.exifStripped === false) {
    // No penalty applied
  } else {
    forensicScore -= 25;
    rationale.push(`EXIF Penalty: -25 (Metadata Stripped)`);
  }

  // B. Resolution Check (Max 25)
  // Logic updated: No longer deducing score based on resolution. 
  // We simply log the resolution for the reviewer's information.
  rationale.push(`Image Resolution: ${forensicFeatures.resolution || "Unknown"} (No Deduction)`);
  
  forensicScore = Math.max(0, forensicScore); 
  score += forensicScore;

  // --- Final Verdict Tier ---
  const totalScore = Math.round(score);
  let finalVerdict;

  if (totalScore >= 400) {
    finalVerdict = "AUTHENTIC & ORIGINAL";
  } else if (totalScore >= 300) {
    finalVerdict = "MODERATE RISK / UNKNOWN";
  } else if (totalScore >= 150) {
    finalVerdict = "HIGH RISK / MODIFIED";
  } else {
    finalVerdict = "PLAGIARIZED / FAKE";
  }

  return { total: totalScore, verdict: finalVerdict, rationale };
}




// AI Detection	        200	      Checks if the pixels were generated by AI.
// Plagiarism	          150	      Checks if the image already exists on the internet.
// LLM Analysis	        70	      Expert visual inspection by Gemini.
// Challenge Match	    30	      Checks if the image matches the prompt/task.
// Forensics	          50	      Checks for original file metadata.
// TOTAL	              500